allowBuilds:
  '@biomejs/biome': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  lefthook: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
